ALTER TABLE "FactoryTemplate"
  ADD COLUMN IF NOT EXISTS "facecamCropZoomPercent" INTEGER NOT NULL DEFAULT 135,
  ADD COLUMN IF NOT EXISTS "facecamCropFocusXPercent" INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS "facecamCropFocusYPercent" INTEGER NOT NULL DEFAULT 50;
